### ISSUE TITLE
angular 2 CLI build prod

### ISSUE THREAD

**Issue by matthewnewman43** [yllieth/angular2-truncate#7]
pipe works perfectly in development but when compiling for production, it throws an error.

Unexpected value 'TruncatePipe in */node_modules/angular2-truncate/dist/pipes/truncate.pipe.d.ts' declared by the module 'AppModule in */src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by nickethan** [comment]
Any luck resolving this? Attempting to build for ionic 2.

**Comment by aluanhaddad** [comment]
I would personally avoid AOT and go back to TypeScript. Then you won't have this problem.

AOT couples you to the framework at a very deep level. Once you start writing AOT code, you are no longer writing in TypeScript or JavaScript but rather in an Angular specific language, that got snuck in under the radar.
